// Author: Gustavo Diaz Galeas (Incapamentum)
// 
// Last revision: March 29th, 2022

#ifndef TRANSACTIONS_H
#define TRANSACTIONS_H

#include <Arduino.h>
#include <Crypto.h>
#include <stdint.h>

#define BLOCK_SIZE 64
#define DATA_LENGTH 2
#define KEY_LENGTH 32
#define SHA1_SIZE 20
// #define SHA256_SIZE 32
#define SHA512_SIZE 64
#define SIGN_LENGTH 64

// Sensor data is collected and packed here
typedef struct
{
    uint8_t temperature;
    uint8_t humidity;
} Data;

// A data transaction that is digitally signed by the device
// that generated it
//
// =========================
//           NOTES
// =========================
//
//      The Transaction class must contain the following:
//          + the data included in the transaction
//          + a 'transactionHash' that uniquely IDs the transaction
//              - generated by hashing 'timestamp', the PK, and the data
//              - hashed using SHA512 (total 512 bits -> 64 bytes)
//          + a 'timestamp' hash using chip ID and actual timestamp
//              - hashed using SHA1 (total 160 bits -> 20 bytes)
//          + the PK of the next/new owner (is always the server -> serverKey_)
//          + a signature of the current/previous owner
//              - generated by signing the 'transactionHash'
class Transaction
{
    private:
        Data data_;
        uint8_t transactionHash_[SHA512_SIZE];
        uint8_t timestamp_[SHA1_SIZE]; // Make sure to test this little routine here
        uint8_t serverKey_[KEY_LENGTH];
        uint8_t signature_[SIGN_LENGTH];

    public:
        Transaction(uint8_t key[KEY_LENGTH]);

        static const size_t transaction_size = 54;

        void setData(uint8_t temp, uint8_t hum);
        void setTimestamp(uint8_t ts[SHA1_SIZE]);
        void hashTransaction(unsigned int chipId);
        int sign(uint8_t deviceKey[KEY_LENGTH]);
};


#endif